using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LanguageLines : MonoBehaviour
{
    public static string[,] lines = {
//ENG
        {
            "Do you want to start a new game? All saves would be lost.",
            "Press on screen",
            "Continue",
            "New game",
            "Settings",
            "Exit",
            "Yes",
            "No",
            "defense",
            "to buy?",
            "attack",
            "coins:",
            "miss",
            "Level up",
            "Greetings. Another adventurer, huh?",
            "Oh well.",
            "This Tower took many lives of rookies like you.",
            "But if you wanna try your luck - welcome.",
            "A bunch of merchants hang around the Tower. You can buy some usefull stuff from them.",
            "I wish you best of luck.",
            "price:",
            "I have the best potions across the town. Have a look!",
            "You won't find this anywhere else!",
            "To town",
            "Have a look at today's products!",
            "Try again",
            "Coins:",
            "Trade",
            "Get in",
            "Go through",
            "CHARACTER",
            "BACK",
            "MAIN MENU",
            "Floor",
            "Equipment",
            "warrior",
            "slot 1",
            "slot 2",
            "learn",
            "archer",
            "mage",
            "Next floor",
            "Back in town",
            "Back",
            "The evil has been defeated.\nFor now...",
            "Level",
            "Health increase",
            "Dash's damage increase",
            "If your health goes down above 10%, your damage will increase",
            "Damage increase",
            "Warrior brings down a series of blows on enemies",
            "Skill",
            "HP",
            "Damage",
            "Knock-off, stun the enemy",
            "Warrior concentrates all strength in 1 strike, making additional damage",
            "Stuns time increase",
            "Warrior sets a banner, increasing HP",
            "Warrior goes a berserk, damage and damage taken increase",
            "Movement speed increase",
            "Movement speed",
            "Vision's range increase",
            "Range",
            "Increases movement speed and add evasion from all damage",
            "Arrows wound enemies and they start bleeding",
            "Chance",
            "Arrows now have chance to explode",
            "Dash's speed increase",
            "Charges bow for a single powerful shot, which go through enemies",
            "Tosses a net at the selected point, pinning down enemies",
            "Archer calls upon the forces of nature, roots appear around you, slowing down enemies",
            "Archer channels the wind to gain additional attack speed",
            "Each shot weakens the enemy",
            "Decrease damage in %",
            "Attacks now have chance to explode",
            "Potions restore more HP",
            "Multiplier",
            "Increase skill damage",
            "Mage concentrates all energy to deal fire damage to enemies around him",
            "Mage concentrates all energy to deal frost damage to enemies around him and freeze them",
            "Your next attack become chain lightning",
            "Abilities cooldown decrease",
            "Decrease",
            "Mage creates energy shield",
            "In selected point mage creates storm that slow enemies and affected enemies take increased damage",
            "Stun"
        },
//RU
        {
            "Действительно начать новую игру? Все сохраненные данные будут потеряны.",
            "Нажми на экран",
            "Продолжить",
            "Новая игра",
            "Настройки",
            "Выход",
            "Да",
            "Нет",
            "защита",
            "купить?",
            "атака",
            "монет:",
            "промах",
            "Новый уровень",
            "Привет. Очередной искатель приключений?",
            "Ну-ну.",
            "Много горячих голов положила эта проклятая Башня.",
            "Но если хочешь попытать счастья - добро пожаловать.",
            "Рядом с Башней ошивается куча торговцев. Можешь поискать что-нибудь у них.",
            "Удачи.",
            "стоим.:",
            "У меня лучшие зелья в городе. Подходи, выбирай!",
            "Смотри, такого ты нигде не найдешь!",
            "В город",
            "Посмотри, что у меня есть сегодня!",
            "Начать заново",
            "Монеты:",
            "Торговать",
            "Войти",
            "Пройти",
            "ИНФОРМАЦИЯ",
            "НАЗАД",
            "В МЕНЮ",
            "Уровень",
            "Предметы",
            "воин",
            "слот 1",
            "слот 2",
            "прокачать",
            "лучник",
            "маг",
            "Следующий уровень",
            "Выйти",
            "Назад",
            "Зло побеждено.\nПока что...",
            "Уровень",
            "Увеличение здоровья",
            "Увеличение урона от скольжения",
            "Если здоровье падает ниже 10%, то воин начинает биться сильнее",
            "Увеличение урона",
            "Воин обрушивает на врагов шквал ударов",
            "Умение",
            "Здоровье",
            "Урон",
            "Удар рукоятью меча, что приводит врагов в замешательство",
            "Воин концентрирует свою энергию, чтобы нанести удар с дополнительным уроном",
            "Увеличение времени от оглушения",
            "Воин ставит знамя, которое увеличивает его здоровье",
            "Воин впадает в ярость, в которой он наносит дополнительный урон, но и урон по нему тоже увеличен",
            "Увеличение скорости бега",
            "Скорость",
            "Увеличение радиуса обзора лучника",
            "Радиус",
            "Увеличение скорости передвижения и позволяет увернуться от всех физических атак",
            "У стрелы повышается шанс вызвать кровотечение у противника",
            "Шанс",
            "У стрелы повышается шанс взорваться",
            "Увеличение скорости скольжения",
            "Лучник заряжает следующую стрелу, которая пробивает противников",
            "В указанную точку лучник выпускает сеть, которая не дает врагам двинуться",
            "Лучник призывает силы природы себе на защиту - вокруг появляются корни, которые замедляют врагов",
            "Лучник направляет ветер, повышая свою скорость атаки",
            "Каждая атака уменьшает силы врага",
            "Уменьшение урона в %",
            "У атаки повышается шанс взорваться",
            "Зелья восстанавливают больше здоровья",
            "Множитель",
            "Урон от всех умений",
            "Маг концентрирует всю свою энергию, чтобы нанести урон огнем вокруг себя",
            "Маг концентрирует всю свою энергию, чтобы нанести урон холодом вокруг себя и замедлить врагов",
            "Цепная молния следующей атакой",
            "Уменьшение времени перезарядки способностей",
            "Уменьшение",
            "Маг обращается к энергии внутри себя, чтобы создать энергетический щит",
            "В указанной точке маг создает ураган, который замедляет противников и делает их более уязвимыми к получаемому урону",
            "Оглушение"
        }
    };

    public static string getLine(int indx)
    {
        return lines[PlayerPrefs.GetInt("CurLanguage"), indx];
    }

    public static string getLine(string indx)
    {
        int I_indx = int.Parse(indx);

        return lines[PlayerPrefs.GetInt("CurLanguage"), I_indx];
    }
}
